# Generated by Django 4.1.1 on 2022-12-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_rename_item_item_product_alter_item_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='detail',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
